const questions = [
    {
        "Question": "Who is edwards dad",
        "correct": "Henry VIII",
        "incorrect1": "john",
        "incorrect2": "lewis",
        "incorrect3": "dave",
        id : 0
    },
    {
        "Question": "who married henry",
        "correct": "anne boleyn",
        "incorrect1": "you",
        "incorrect2": "me",
        "incorrect3": "i",
        id : 1,
    },
    {
        "Question": "1",
        "correct": "2",
        "incorrect1": "3",
        "incorrect2": "4",
        "incorrect3": "5",
        id : 2,
    },
    {
        "Question": "a",
        "correct": "b",
        "incorrect1": "c",
        "incorrect2": "d",
        "incorrect3": "e",
        id : 3,
    },
    {
        "Question": "games",
        "correct": "fps",
        "incorrect1": "action",
        "incorrect2": "adventure",
        "incorrect3": "story",
        id : 4,
    },
    {
        "Question": "sports",
        "correct": "bb",
        "incorrect1": "football",
        "incorrect2": "rugby",
        "incorrect3": "golf",
        id : 5,
    },
    {
        "Question": "perfume",
        "correct": "arab",
        "incorrect1": "designer",
        "incorrect2": "niche",
        "incorrect3": "deo",
        id : 6,
    },
    {
        "Question": "drinks",
        "correct": "water",
        "incorrect1": "juice",
        "incorrect2": "fizzy",
        "incorrect3": "milk",
        id : 7,
    },
    {
        "Question": "food",
        "correct": "rice",
        "incorrect1": "noodles",
        "incorrect2": "bread",
        "incorrect3": "meat",
        id : 8,
    },
    {
        "Question": "team",
        "correct": "team1",
        "incorrect1": "team2",
        "incorrect2": "team3",
        "incorrect3": "team4",
        id : 9,
    }
]
module.exports = questions
